# Neural Networks in PyTorch
## Chapter 1: Neural Network Layers
*Yen Lee Loh, 2021-9-1; 2022-9-22*

In this Jupyter Lab notebook we demonstrate elementwise layers, linear layers, loss functions, pooling layers, and convolution layers.

---
## 0.  Setup

In [1]:
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
rng = np.random.default_rng()
plt.rcParams.update ({'font.family':'serif', 'font.size':14})

---
## 1. Some stuff

Many array-like (container) data types in Python 
- some built-in to the language
- some are provided by external libraries, e.g., numpy, torch

        dict    
        set      s = {1,2,3}      (curly braces)
        tuple    t = (1,2,3)      (round parentheses)
        list     l = [1,2,3]      (square brackets)           - no. 2 choice
        
        numpy.ndarray   a = np.array ([[1,2,3],[4,5,6]])      - no. 1 choice
        torch.Tensor    a = torch.Tensor ([[1,2,3],[4,5,6]])      - no. 3 choice

Most PyTorch tensors and functions behave very much like the corresponding things in NumPy.

In [4]:
l=[1,2,3]

In [18]:
a = np.array ([[1,2.,3],[4,5,6]])

In [14]:
b = torch.Tensor ([[1,2,3],[4,5,6]])

In [24]:
type(a)

numpy.ndarray

In [21]:
a.dtype

dtype('float64')

In [26]:
len(a)

2

In [27]:
a.shape

(2, 3)

In [28]:
a.size

6

In [19]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
a[1,2]   # element of array a in row 1 and column 2 (counting from 0!)

6.0

In [17]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [29]:
b[1,2]

tensor(6.)

In [30]:
b.shape

torch.Size([2, 3])

You can interconvert between list, array, and Tensor.

In [53]:
l = [1,2,3]

a = np.array(l)     # convert list to numpy.array
l = list(a)         # convert numpy.array to list
l = a.tolist()      # convert numpy.array to list

b = torch.Tensor(l) # convert list to torch.Tensor
l = b.tolist()
print ('l =', l)    # convert torch.Tensor to list

b = torch.Tensor(a) # convert numpy.array to torch.Tensor
a = np.array(b)     # convert torch.Tensor to numpy.array
a = b.numpy()       # convert torch.Tensor to numpy.array
#print ('b =', b)
print ('a =', a)


l = [1.0, 2.0, 3.0]
a = [1. 2. 3.]


In [54]:
a

array([1., 2., 3.], dtype=float32)

In [40]:
a

array([1, 2, 3])

In [41]:
l

[1, 2, 3]