In [7]:
import numpy as np

In [6]:
3*[4,5,6] + [2,3]

[4, 5, 6, 4, 5, 6, 4, 5, 6, 2, 3]

In [10]:
np.array ([4,5,6]) + np.array ([1,2,3]

array([5, 7, 9])

# Using numpy.roll and torch.roll
## Extracting "Features" G4 and G5 for FerroelectricML project
### Yen Lee Loh, 2021-9-6

In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt

---

## 1. numpy.roll in cardinal directions (along a single axis)

### Observe how the number "55" moves when numpy.roll is applied to the matrix.

In [7]:
Pij = np.array ([[1,2,3,0],[4,55,6,0],[7,8,9,0]])
print ("\nP[i,j] = original matrix"); print(Pij)
print ("\nP[i-1,j] = matrix rolled by +1 in dimension 0 (i -> i+1)"); print (np.roll (Pij, +1, 0))
print ("\nP[i+1,j] = matrix rolled by -1 in dimension 0 (i -> i-1)"); print (np.roll (Pij, -1, 0))
print ("\nP[i,j-1] = matrix rolled by +1 in dimension 1 (j -> j+1)"); print (np.roll (Pij, +1, 1))
print ("\nP[i,j+1] = matrix rolled by -1 in dimension 1 (j -> j-1)"); print (np.roll (Pij, -1, 1))


P[i,j] = original matrix
[[ 1  2  3  0]
 [ 4 55  6  0]
 [ 7  8  9  0]]

P[i-1,j] = matrix rolled by +1 in dimension 0 (i -> i+1)
[[ 7  8  9  0]
 [ 1  2  3  0]
 [ 4 55  6  0]]

P[i+1,j] = matrix rolled by -1 in dimension 0 (i -> i-1)
[[ 4 55  6  0]
 [ 7  8  9  0]
 [ 1  2  3  0]]

P[i,j-1] = matrix rolled by +1 in dimension 1 (j -> j+1)
[[ 0  1  2  3]
 [ 0  4 55  6]
 [ 0  7  8  9]]

P[i,j+1] = matrix rolled by -1 in dimension 1 (j -> j-1)
[[ 2  3  0  1]
 [55  6  0  4]
 [ 8  9  0  7]]


## 2. numpy.roll in general direction, including diagonal or oblique directions

### This is my preferred syntax, since it is most general.

In [9]:
print ("\nP[i,j] = original matrix"); print (Pij)
print ("\nP[i-1,j] = matrix rolled such that i->i+1 and j->j+0"); print (np.roll (Pij, (+1, 0), axis=(0,1)))
print ("\nP[i-1,j-1] = matrix rolled such that i->i+1 and j->j+1"); print (np.roll (Pij, (+1,+1), axis=(0,1)))
print ("\nP[i-1,j-2] = matrix rolled such that i->i+1 and j->j+2"); print (np.roll (Pij, (+1,+2), axis=(0,1)))


P[i,j] = original matrix
[[ 1  2  3  0]
 [ 4 55  6  0]
 [ 7  8  9  0]]

P[i-1,j] = matrix rolled such that i->i+1 and j->j+0
[[ 7  8  9  0]
 [ 1  2  3  0]
 [ 4 55  6  0]]

P[i-1,j-1] = matrix rolled such that i->i+1 and j->j+1
[[ 0  7  8  9]
 [ 0  1  2  3]
 [ 0  4 55  6]]

P[i-1,j-2] = matrix rolled such that i->i+1 and j->j+2
[[ 9  0  7  8]
 [ 3  0  1  2]
 [ 6  0  4 55]]


## 3. torch.roll

### You can do the same thing with PyTorch.

In [10]:
Pij = torch.tensor ([[1,2,3,0],[4,55,6,0],[7,8,9,0]])
print ("\nP[i,j] = original matrix"); print(Pij)
print ("\nP[i-1,j] = matrix rolled by +1 in dimension 0 (i -> i+1)"); print (torch.roll (Pij, +1, 0))
print ("\nP[i+1,j] = matrix rolled by -1 in dimension 0 (i -> i-1)"); print (torch.roll (Pij, -1, 0))
print ("\nP[i,j-1] = matrix rolled by +1 in dimension 1 (j -> j+1)"); print (torch.roll (Pij, +1, 1))
print ("\nP[i,j+1] = matrix rolled by -1 in dimension 1 (j -> j-1)"); print (torch.roll (Pij, -1, 1))


P[i,j] = original matrix
tensor([[ 1,  2,  3,  0],
        [ 4, 55,  6,  0],
        [ 7,  8,  9,  0]])

P[i-1,j] = matrix rolled by +1 in dimension 0 (i -> i+1)
tensor([[ 7,  8,  9,  0],
        [ 1,  2,  3,  0],
        [ 4, 55,  6,  0]])

P[i+1,j] = matrix rolled by -1 in dimension 0 (i -> i-1)
tensor([[ 4, 55,  6,  0],
        [ 7,  8,  9,  0],
        [ 1,  2,  3,  0]])

P[i,j-1] = matrix rolled by +1 in dimension 1 (j -> j+1)
tensor([[ 0,  1,  2,  3],
        [ 0,  4, 55,  6],
        [ 0,  7,  8,  9]])

P[i,j+1] = matrix rolled by -1 in dimension 1 (j -> j-1)
tensor([[ 2,  3,  0,  1],
        [55,  6,  0,  4],
        [ 8,  9,  0,  7]])


---
## 4. Computing nearest-neighbor differences on a lattice with periodic boundary conditions

In [11]:
Pij = torch.tensor ([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print ("\nOriginal matrix:                     P[i,j] = \n", Pij)
print ("\nForward difference between rows:     P[i+1,j] - P[i,j] = \n",   torch.roll(Pij,-1,0) - Pij  )
print ("\nForward difference between columns:  P[i,j+1] - P[i,j] = \n",   torch.roll(Pij,-1,1) - Pij  )


Original matrix:                     P[i,j] = 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

Forward difference between rows:     P[i+1,j] - P[i,j] = 
 tensor([[  4,   4,   4,   4],
        [  4,   4,   4,   4],
        [  4,   4,   4,   4],
        [-12, -12, -12, -12]])

Forward difference between columns:  P[i,j+1] - P[i,j] = 
 tensor([[ 1,  1,  1, -3],
        [ 1,  1,  1, -3],
        [ 1,  1,  1, -3],
        [ 1,  1,  1, -3]])


In [12]:
Pij = torch.tensor ([[5,5,5,5],[7,7,7,7],[6,6,6,6],[3,3,3,3]])
print ("\nConfiguration with horizontal stripes: P[i,j] = \n", Pij)
print ("Sum of squares of vertical differences:    sum_{ij} (P[i+1,j] - P[i,j])^2 = ",   torch.sum((torch.roll(Pij,-1,0) - Pij)**2).item()  )
print ("Sum of squares of horizontal differences:  sum_{ij} (P[i,j+1] - P[i,j])^2 = ",   torch.sum((torch.roll(Pij,-1,1) - Pij)**2).item()  )
Pij = torch.tensor ([[5,5,5,5],[7,7,7,7],[6,6,6,6],[3,3,3,3]]).T
print ("\nConfiguration with vertical stripes: P[i,j] = \n", Pij)
print ("Sum of squares of vertical differences:    sum_{ij} (P[i+1,j] - P[i,j])^2 = ",   torch.sum((torch.roll(Pij,-1,0) - Pij)**2).item()  )
print ("Sum of squares of horizontal differences:  sum_{ij} (P[i,j+1] - P[i,j])^2 = ",   torch.sum((torch.roll(Pij,-1,1) - Pij)**2).item()  )
Pij = torch.tensor ([[2,9,2,9],[9,2,9,2],[2,9,2,9],[9,2,9,2]]).T
print ("\nCheckerboard configuration: P[i,j] = \n", Pij)
print ("Sum of squares of vertical differences:    sum_{ij} (P[i+1,j] - P[i,j])^2 = ",   torch.sum((torch.roll(Pij,-1,0) - Pij)**2).item()  )
print ("Sum of squares of horizontal differences:  sum_{ij} (P[i,j+1] - P[i,j])^2 = ",   torch.sum((torch.roll(Pij,-1,1) - Pij)**2).item()  )


Configuration with horizontal stripes: P[i,j] = 
 tensor([[5, 5, 5, 5],
        [7, 7, 7, 7],
        [6, 6, 6, 6],
        [3, 3, 3, 3]])
Sum of squares of vertical differences:    sum_{ij} (P[i+1,j] - P[i,j])^2 =  72
Sum of squares of horizontal differences:  sum_{ij} (P[i,j+1] - P[i,j])^2 =  0

Configuration with vertical stripes: P[i,j] = 
 tensor([[5, 7, 6, 3],
        [5, 7, 6, 3],
        [5, 7, 6, 3],
        [5, 7, 6, 3]])
Sum of squares of vertical differences:    sum_{ij} (P[i+1,j] - P[i,j])^2 =  0
Sum of squares of horizontal differences:  sum_{ij} (P[i,j+1] - P[i,j])^2 =  72

Checkerboard configuration: P[i,j] = 
 tensor([[2, 9, 2, 9],
        [9, 2, 9, 2],
        [2, 9, 2, 9],
        [9, 2, 9, 2]])
Sum of squares of vertical differences:    sum_{ij} (P[i+1,j] - P[i,j])^2 =  784
Sum of squares of horizontal differences:  sum_{ij} (P[i,j+1] - P[i,j])^2 =  784
